from __future__ import annotations

from io import BytesIO
from pathlib import Path

from reportlab.graphics.shapes import Circle, Drawing, Line, Rect, String
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from .models import AnalysisReport, Coordinate, EvacuationRoute, HazardZone, SafeZone


class EmergencyPDFBuilder:
    def build_pdf(self, report: AnalysisReport, output_path: str | Path | None = None) -> bytes:
        buffer = BytesIO()
        document = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=14 * mm,
            rightMargin=14 * mm,
            topMargin=16 * mm,
            bottomMargin=16 * mm,
        )
        styles = getSampleStyleSheet()
        styles.add(
            ParagraphStyle(
                name="SectionTitle",
                parent=styles["Heading2"],
                textColor=colors.HexColor("#143642"),
                spaceAfter=6,
                fontName="Helvetica-Bold",
            )
        )
        styles.add(
            ParagraphStyle(
                name="BodyTight",
                parent=styles["BodyText"],
                leading=14,
                spaceAfter=4,
            )
        )

        story = [
            Paragraph("Disaster Detection AI Emergency Situation Report", styles["Title"]),
            Paragraph(report.executive_summary, styles["BodyText"]),
            Spacer(1, 8),
            Paragraph("Executive Summary", styles["SectionTitle"]),
            self._facts_table(
                [
                    ("Report ID", report.report_id),
                    ("Disaster Type", report.request.disaster_type.title()),
                    ("Severity", report.risk_assessment.severity_level),
                    ("Affected Regions", ", ".join(report.situation_analysis.affected_regions)),
                    ("Timestamp", report.generated_at.isoformat()),
                ]
            ),
            Spacer(1, 8),
            Paragraph("Situation Analysis", styles["SectionTitle"]),
            Paragraph(report.situation_analysis.incident_summary, styles["BodyTight"]),
            Paragraph(report.situation_analysis.threat_assessment, styles["BodyTight"]),
            Paragraph(report.situation_analysis.current_incident_status, styles["BodyTight"]),
            self._facts_table(
                [
                    ("Population at Risk", f"{report.situation_analysis.population_at_risk:,}"),
                    ("Hospitals at Risk", str(report.situation_analysis.hospitals_at_risk)),
                    ("Schools at Risk", str(report.situation_analysis.schools_at_risk)),
                    ("Roads Blocked", str(report.situation_analysis.roads_blocked)),
                    ("Damage Estimate", report.situation_analysis.infrastructure_damage_estimate),
                ]
            ),
            Spacer(1, 8),
            Paragraph("Safe Zones and Shelter Information", styles["SectionTitle"]),
            self._safe_zone_table(report.safe_zones),
            Spacer(1, 8),
            Paragraph("Safe Zone Map", styles["SectionTitle"]),
            self._map_drawing(report),
            Spacer(1, 8),
            Paragraph("Evacuation Instructions", styles["SectionTitle"]),
            self._route_table(report.evacuation_routes),
            Spacer(1, 8),
            Paragraph("Precautionary Measures", styles["SectionTitle"]),
            Paragraph("<b>Before:</b> " + " ".join(report.precautionary_measures.before_disaster), styles["BodyTight"]),
            Paragraph("<b>During:</b> " + " ".join(report.precautionary_measures.during_disaster), styles["BodyTight"]),
            Paragraph("<b>After:</b> " + " ".join(report.precautionary_measures.after_disaster), styles["BodyTight"]),
            Spacer(1, 8),
            Paragraph("Emergency Supply Checklist", styles["SectionTitle"]),
            Paragraph(", ".join(report.emergency_supply_checklist), styles["BodyTight"]),
            Spacer(1, 8),
            Paragraph("Emergency Contacts", styles["SectionTitle"]),
            self._facts_table(list(report.emergency_contacts.items())),
            Spacer(1, 8),
            Paragraph("AI Recommendations", styles["SectionTitle"]),
            Paragraph(" | ".join(report.recommended_actions), styles["BodyTight"]),
            Paragraph(" | ".join(report.resource_allocation_suggestions), styles["BodyTight"]),
            Spacer(1, 8),
            Paragraph("Report Metadata", styles["SectionTitle"]),
            self._facts_table(
                [
                    ("Generated By", report.generated_by),
                    ("Data Sources Used", ", ".join(report.data_sources_used)),
                    ("MCP Tools Utilized", ", ".join(report.mcp_tools_utilized)),
                ]
            ),
        ]
        document.build(story)
        pdf_bytes = buffer.getvalue()
        if output_path is not None:
            Path(output_path).write_bytes(pdf_bytes)
        return pdf_bytes

    def _facts_table(self, rows: list[tuple[str, str]]) -> Table:
        table = Table(rows, colWidths=[42 * mm, 128 * mm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E6F2F2")),
                    ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#143642")),
                    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#A9C5C6")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        return table

    def _safe_zone_table(self, safe_zones: list[SafeZone]) -> Table:
        rows = [["Shelter", "Capacity", "Distance", "Contact", "Notes"]]
        for zone in safe_zones:
            rows.append(
                [
                    zone.name,
                    f"{zone.available_capacity}/{zone.capacity}",
                    f"{zone.distance_km} km",
                    zone.contact,
                    " ".join(zone.notes[:2]),
                ]
            )
        table = Table(rows, colWidths=[42 * mm, 25 * mm, 22 * mm, 34 * mm, 57 * mm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#143642")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#A9C5C6")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("PADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        return table

    def _route_table(self, routes: list[EvacuationRoute]) -> Table:
        rows = [["Route", "Distance", "ETA", "Safety", "Route Safety Notes"]]
        for route in routes:
            rows.append(
                [
                    route.safe_zone_name,
                    f"{route.distance_km} km",
                    f"{route.travel_time_min} min",
                    f"{route.safety_score}",
                    " ".join(route.notes),
                ]
            )
        table = Table(rows, colWidths=[42 * mm, 24 * mm, 20 * mm, 20 * mm, 94 * mm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E17A47")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D0A48A")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("PADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        return table

    def _map_drawing(self, report: AnalysisReport) -> Drawing:
        width = 170 * mm
        height = 90 * mm
        drawing = Drawing(width, height)
        drawing.add(Rect(0, 0, width, height, strokeColor=colors.HexColor("#29434E"), fillColor=colors.HexColor("#F3F6F4")))
        scale_x = width / 100
        scale_y = height / 100

        for region in report.map_layers["regions"]:
            bounds = region["bounds"]
            drawing.add(
                Rect(
                    bounds["x"] * scale_x,
                    bounds["y"] * scale_y,
                    bounds["width"] * scale_x,
                    bounds["height"] * scale_y,
                    strokeColor=colors.HexColor("#C7D4CC"),
                    fillColor=colors.HexColor("#EDF2EE"),
                )
            )
            drawing.add(
                String(
                    (bounds["x"] + 2) * scale_x,
                    (bounds["y"] + bounds["height"] - 5) * scale_y,
                    region["name"],
                    fontSize=7,
                    fillColor=colors.HexColor("#29434E"),
                )
            )

        for hazard in report.hazard_zones:
            drawing.add(
                Circle(
                    hazard.center.x * scale_x,
                    hazard.center.y * scale_y,
                    hazard.radius * scale_x,
                    fillColor=colors.Color(0.85, 0.20, 0.18, alpha=0.20),
                    strokeColor=colors.HexColor("#D64541"),
                )
            )
            drawing.add(
                String(
                    (hazard.center.x - 5) * scale_x,
                    hazard.center.y * scale_y,
                    hazard.name,
                    fontSize=7,
                    fillColor=colors.HexColor("#922B21"),
                )
            )

        for route in report.evacuation_routes:
            for start, end in zip(route.path[:-1], route.path[1:]):
                drawing.add(
                    Line(
                        start.x * scale_x,
                        start.y * scale_y,
                        end.x * scale_x,
                        end.y * scale_y,
                        strokeColor=colors.HexColor("#0F7173"),
                        strokeWidth=2,
                    )
                )

        for zone in report.safe_zones:
            self._draw_safe_zone(drawing, zone, scale_x, scale_y)

        current = Coordinate(**report.map_layers["current_location"])
        drawing.add(
            Circle(
                current.x * scale_x,
                current.y * scale_y,
                4,
                fillColor=colors.HexColor("#162521"),
                strokeColor=colors.white,
                strokeWidth=1,
            )
        )
        drawing.add(
            String(
                (current.x + 2) * scale_x,
                current.y * scale_y,
                "Current Location",
                fontSize=7,
                fillColor=colors.HexColor("#162521"),
            )
        )
        return drawing

    @staticmethod
    def _draw_safe_zone(drawing: Drawing, zone: SafeZone, scale_x: float, scale_y: float) -> None:
        size = 5
        x = zone.location.x * scale_x
        y = zone.location.y * scale_y
        drawing.add(
            Rect(
                x - size / 2,
                y - size / 2,
                size,
                size,
                fillColor=colors.HexColor("#18A999"),
                strokeColor=colors.HexColor("#0F7173"),
            )
        )
        drawing.add(
            String(
                (zone.location.x + 1.5) * scale_x,
                zone.location.y * scale_y + 4,
                zone.name,
                fontSize=7,
                fillColor=colors.HexColor("#0F7173"),
            )
        )
